//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public long UserId { get; set; }
        public string UserPw { get; set; }
        public string UserName { get; set; }
        public string UserFullName { get; set; }
        public System.DateTime UserDob { get; set; }
        public Nullable<long> UserGender { get; set; }
        public string UserAddress { get; set; }
        public string UserMobile { get; set; }
        public string UserEmail { get; set; }
        public long StudentId { get; set; }
        public long UserType { get; set; }
        public string UserAvatar { get; set; }
    
        public virtual Student Student { get; set; }

        public Parent()
        {
            this.Student = new Student();
        }
    }
}
