//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.CourseStudentDetails = new HashSet<CourseStudentDetail>();
            this.Parents = new HashSet<Parent>();
            this.TaskDetails = new HashSet<TaskDetail>();
        }
    
        public long UserId { get; set; }
        public string IdentificationCode { get; set; }
        public string UserPw { get; set; }
        public string UserName { get; set; }
        public string UserFullName { get; set; }
        public System.DateTime UserDob { get; set; }
        public Nullable<long> UserGender { get; set; }
        public string UserAddress { get; set; }
        public string UserMobile { get; set; }
        public string UserEmail { get; set; }
        public Nullable<double> TotalTuTition { get; set; }
        public Nullable<double> TotalinDebt { get; set; }
        public long UserType { get; set; }
        public string UserAvatar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseStudentDetail> CourseStudentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parent> Parents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskDetail> TaskDetails { get; set; }
    }
}
