//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskDetails = new HashSet<TaskDetail>();
            this.Course = new Course();
        }
    
        public long TaskId { get; set; }
        public string TaskName { get; set; }
        public long CourseId { get; set; }
        public string TaskDescription { get; set; }
        public string TaskContent { get; set; }
        public System.DateTime TaskDateStart { get; set; }
        public System.DateTime TaskDeadline { get; set; }
        public Nullable<System.DateTime> TaskDateSubmission { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskDetail> TaskDetails { get; set; }
    }
}
