USE COURSES_MANAGEMENT

ALTER TABLE PARENT
ADD CONSTRAINT FK_PARENT_STUDENT FOREIGN KEY(CHILDID) REFERENCES STUDENT(ID)

ALTER TABLE STUDENT
ADD CONSTRAINT FK_STUDENT_PARENT FOREIGN KEY(PARENTID) REFERENCES PARENT(ID)

ALTER TABLE COURSE
ADD CONSTRAINT FK_COURSE_TEACHER FOREIGN KEY(MANAGERID) REFERENCES TEACHER(ID)

ALTER TABLE CLASS
ADD CONSTRAINT FK_CLASS_COURSE FOREIGN KEY(COURSEID) REFERENCES COURSE(ID)

ALTER TABLE TASK
ADD CONSTRAINT FK_TASK_CLASS FOREIGN KEY(CLASSID, COURSEID) REFERENCES CLASS(ID, COURSEID)

ALTER TABLE LECTURE
ADD CONSTRAINT FK_LECTURE_CLASS FOREIGN KEY(CLASSID, COURSEID) REFERENCES CLASS(ID, COURSEID)

ALTER TABLE TEACHING_ASSIGNMENT
ADD CONSTRAINT FK_TEACHING_ASSIGNMENT_TEACHER FOREIGN KEY(TEACHERID) REFERENCES TEACHER(ID),
CONSTRAINT FK_TEACHING_ASSIGNMENT_CLASS FOREIGN KEY(CLASSID, COURSEID) REFERENCES CLASS(ID, COURSEID)

ALTER TABLE CLASS_ENROLLMENT
ADD CONSTRAINT FK_CLASS_ENROLLMENT_STUDENT FOREIGN KEY(STUDENTID) REFERENCES STUDENT(ID),
CONSTRAINT FK_CLASS_ENROLLMENT_CLASS FOREIGN KEY(CLASSID, COURSEID) REFERENCES CLASS(ID, COURSEID)

ALTER TABLE TASK_SUBMISSION
ADD CONSTRAINT FK_TASK_SUBMISSION_STUDENT FOREIGN KEY (STUDENTID) REFERENCES STUDENT(ID)

ALTER TABLE TASK_SUBMISSION
ADD CONSTRAINT FK_TASK_SUBMISSION_TASK FOREIGN KEY (TASKID, COURSEID, CLASSID) REFERENCES TASK(ID, COURSEID, CLASSID)
