USE COURSES_MANAGEMENT
SET ANSI_NULLS ON

/*CREATE TABLE SCRIPT*/
CREATE TABLE STUDENT
(
	ID CHAR(7) NOT NULL,
	PARENTID CHAR(10) NULL,
	/*Common info*/
	PASSWORD_ CHAR(15) NOT NULL,
	FULLNAME NVARCHAR(50) NOT NULL,
	DOB DATE NOT NULL,
	GENDER NVARCHAR(3) NOT NULL,
	ADDRESS_ NVARCHAR(100) NULL,
	MOBILE CHAR(10) NULL,
	EMAIL CHAR(40) NULL,
	/*Common info*/
	CONSTRAINT PK_STUDENT PRIMARY KEY(ID),
	CONSTRAINT C_STUDENT_GENDER CHECK(GENDER IN (N'Nam',N'Nữ'))
)

CREATE TABLE PARENT
(
	ID CHAR(10) NOT NULL,
	CHILDID CHAR(7) NOT NULL,
	/*Common info*/
	PASSWORD_ CHAR(15) NOT NULL,
	FULLNAME NVARCHAR(50) NOT NULL,
	DOB DATE NULL,
	GENDER NVARCHAR(3) NOT NULL,
	ADDRESS_ NVARCHAR(100) NULL,
	MOBILE CHAR(10) NULL,
	EMAIL CHAR(40) NULL,
	/*Common info*/
	CONSTRAINT PK_PARENT PRIMARY KEY(ID),
	CONSTRAINT C_PARENT_GENDER CHECK(GENDER IN (N'Nam',N'Nữ'))
)

CREATE TABLE TEACHER
(
	ID CHAR(7) NOT NULL,
	ISMANAGER BIT NULL,
	/*Common info*/
	PASSWORD_ CHAR(15) NOT NULL,
	FULLNAME NVARCHAR(50) NOT NULL,
	DOB DATE NULL,
	GENDER NVARCHAR(3) NOT NULL,
	ADDRESS_ NVARCHAR(100) NULL,
	MOBILE CHAR(10) NULL,
	EMAIL CHAR(40) NULL,
	/*Common info*/
	CONSTRAINT PK_TEACHER PRIMARY KEY(ID),
	CONSTRAINT C_TEACHER_GENDER CHECK(GENDER IN (N'Nam', N'Nữ'))
)

CREATE TABLE COURSE
(
	ID CHAR(7) NOT NULL,
	MANAGERID CHAR(7) NOT NULL,
	NUMBEROFCLASSES INT NOT NULL,
	COURSENAME NVARCHAR(50) NOT NULL,
	DATE_START DATE NOT NULL,
	DATE_END DATE NOT NULL,
	CONSTRAINT PK_COURSE PRIMARY KEY(ID)
)

CREATE TABLE CLASS
(
	ID CHAR(15) NOT NULL,
	COURSEID CHAR(7) NOT NULL,
	CLASSNAME NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_CLASS PRIMARY KEY(ID,COURSEID)
)

CREATE TABLE TASK
(
	ID CHAR(3) NOT NULL,
	COURSEID CHAR(7) NOT NULL,
	CLASSID CHAR(15) NOT NULL,
	TASKNAME NVARCHAR(50) NOT NULL,
	DATE_ASSIGNED SMALLDATETIME NOT NULL,
	DEADLINE SMALLDATETIME NOT NULL,
	CONTENT NVARCHAR(256) NOT NULL,
	CONSTRAINT PK_TASK PRIMARY KEY(ID, COURSEID, CLASSID)
)

CREATE TABLE LECTURE
(
	ID CHAR(3) NOT NULL,
	COURSEID CHAR(7) NOT NULL,
	CLASSID CHAR(15) NOT NULL,
	LECTURENAME NVARCHAR(50) NOT NULL,
	DATEUPLOADED DATE NOT NULL,
	CONTENT NVARCHAR(256) NOT NULL
	CONSTRAINT PK_LECTURE PRIMARY KEY(ID, COURSEID, CLASSID)
)

CREATE TABLE TEACHING_ASSIGNMENT
(
	TEACHERID CHAR(7) NOT NULL,
	COURSEID CHAR(7) NOT NULL,
	CLASSID CHAR(15) NOT NULL,
	CONSTRAINT PK_TEACHING_ASSIGNMENT PRIMARY KEY(TEACHERID, COURSEID, CLASSID)
)

CREATE TABLE CLASS_ENROLLMENT
(
	STUDENTID CHAR(7) NOT NULL,
	COURSEID CHAR(7) NOT NULL,
	CLASSID CHAR(15) NOT NULL,
	CONSTRAINT PK_CLASS_ENROLLMENT PRIMARY KEY (STUDENTID, COURSEID, CLASSID)
)

CREATE TABLE TASK_SUBMISSION
(
	STUDENTID CHAR(7) NOT NULL,
	TASKID CHAR(3) NOT NULL,
	COURSEID CHAR(7) NOT NULL,
	CLASSID CHAR(15) NOT NULL,
	DATESUBMITTED SMALLDATETIME NOT NULL,
	CONTENT NVARCHAR(256) NOT NULL,
	CONSTRAINT PK_TASK_SUBMISSION PRIMARY KEY(STUDENTID, TASKID, COURSEID, CLASSID)
)
